---
- name: test if kernel_version is set correctly
  assert:
    that:
      - kernel_version is defined
    quiet: yes

- name: test if kernel_build_location is set correctly
  assert:
    that:
      - kernel_build_location is defined
    quiet: yes

- name: test if kernel_parameters is set correctly
  assert:
    that:
      - kernel_parameters is iterable
    quiet: yes
  when:
    - kernel_parameters is defined

- name: test if item in kernel_parameters is set correctly
  assert:
    that:
      - item.name is defined
      - item.value is defined
      - item.value in [ "y", "n", "m" ]
    quiet: yes
  loop: "{{ kernel_parameters }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - kernel_parameters is defined
